/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.ui;


import java.awt.event.ActionListener;
import javax.swing.event.AncestorListener;

/**
 *
 * @author rpv0237
 */
public class Conversation extends javax.swing.JPanel {

    /**
     * Creates new form Conversation
     */
    public Conversation() {
        initComponents();
    }
    
    public void setActionListener(ActionListener e){
        this.conversation_take.addActionListener(e);
        this.conversation_cancel.addActionListener(e);
    }
    
    public void setLabelContent(String str){
        this.jLabel1.setText(str);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        conversation_take = new javax.swing.JButton();
        conversation_cancel = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        conversation_take.setText("conversation_take");

        conversation_cancel.setText("conversation_cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(conversation_take)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(conversation_cancel)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conversation_take)
                    .addComponent(conversation_cancel))
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conversation_cancel;
    private javax.swing.JButton conversation_take;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
