/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.ui;

import game.Direction;
import game.Game;
import java.awt.Color;
import javax.swing.ImageIcon;
import model.Building;
import model.MapSquare;
import model.Mountain;
import model.Portal;
import model.Position;
import model.Rock;
import model.Sand;
import model.Tree;
import model.Water;
import model.Xman;

/**
 *
 * @author rpv0237
 */
public class MapSquarePanel extends javax.swing.JPanel {

    /**
     * Creates new form MapSquarePanel
     */
    
    private Game game;
    private int row;
    private int column;
    
    public MapSquarePanel(Game game, int row, int column) {
        this.game = game;
        this.row = row;
        this.column = column;
        this.setBounds(0, 0, 30, 30);
        initComponents();
    }
    
    public void update(){
        
        MapSquare mapSquare = this.game.getWorld().getMapSquare()[this.row][this.column];
        if(mapSquare instanceof Sand){
            setBackground(Color.YELLOW);
            lblContents.setIcon(new ImageIcon("src/image/sand.png"));
        }else if(mapSquare instanceof Tree){
            setBackground(Color.GREEN);
            lblContents.setIcon(new ImageIcon("src/image/tree.png"));
        }else if(mapSquare instanceof Mountain){
            setBackground(Color.GRAY);
            lblContents.setIcon(new ImageIcon("src/image/mountain.png"));
        }else if(mapSquare instanceof Water){
            setBackground(Color.BLUE);
            lblContents.setIcon(new ImageIcon("src/image/water.png"));
        }else if(mapSquare instanceof Building){
            setBackground(Color.DARK_GRAY);
            lblContents.setIcon(new ImageIcon("src/image/building.png"));
        }else if(mapSquare instanceof Rock){
            setBackground(Color.ORANGE);
            lblContents.setIcon(new ImageIcon("src/image/rock.png"));
        }else if(mapSquare instanceof Portal){
            setBackground(Color.CYAN);
            lblContents.setIcon(new ImageIcon("src/image/portal.gif"));
        }
        if(mapSquare.getOccupantsAsArray().length == 2){
            setBackground(Color.RED);
        }else if(mapSquare.getOccupantStringRepresentation().equals("X")){
            setBackground(Color.BLACK);
            this.game.setXman(new Xman(new Position(this.game.getWorld(), this.row, this.column)));
        }else if(mapSquare.getOccupantStringRepresentation().equals("H")){
            lblContents.setIcon(new ImageIcon("src/image/lancer.png"));
        }else if(mapSquare.getOccupantStringRepresentation().equals("O")){
            lblContents.setIcon(new ImageIcon("src/image/lancer.png"));
        }else if(mapSquare.getOccupantStringRepresentation().equals("Z")){
            lblContents.setIcon(new ImageIcon("src/image/lancer.png"));
        }
    }
    
    public void setPlayer(Direction direction){
        MapSquare mapSquare = this.game.getWorld().getMapSquare()[this.game.getPlayer().getPosition().getRow()][this.game.getPlayer().getPosition().getColumn()];
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblContents = new javax.swing.JLabel();

        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(30, 30));
        setLayout(new java.awt.BorderLayout());

        lblContents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContents.setToolTipText("");
        add(lblContents, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblContents;
    // End of variables declaration//GEN-END:variables
}
